kind: ConfigMap
apiVersion: v1
metadata:
  name: demo-app
  namespace: development
data:
  APP_NAME: Demo
  APP_ENV: development
  APP_KEY: base64:QJKvhZRjMbkFqmG93pYSH68IFSi1Th0lhLH3+PUL1Pc=
  APP_DEBUG: "true"
  APP_URL: http://localhost

  LOG_CHANNEL: stack

  DB_CONNECTION: pgsql
  DB_HOST: app-postgresql-master.cbckp8nutrni.eu-central-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_DATABASE: appPostgresql
  DB_USERNAME: app_postgresql
  DB_PASSWORD: "YourPwdShouldBeLongAndSecure!"

  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"

  MAIL_MAILER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "null"
  MAIL_FROM_NAME: "${APP_NAME}"
